
system:
  email: "email.to@send.from"

sites:
  ecse318:
    url: "url1"
    user: "username1"
    password: "password1"
    emails:
      - "Ilovesaab@gmail.com"
      - "saabneedsanotificationserver@case.edu"
    user_db: "something for future"
  ecse485:
    url: "url2"
    user: "username2"
    password: "password2"
    emails:
      - "Ilovesaab@gmail.com"
      - "saabneedsanotificationserver@case.edu"
    user_db: "something for future 2"
  ecse315:
    url: "url3"
    user: "username3"
    password: "password3"
    emails:
      - "Ilovesaab@gmail.com"
      - "saabneedsanotificationserver@case.edu"
    user_db: "something for future 2"
