
system:
  discord_hook: "https://something"
  admin_hook: "https://something"
  var_path: "/var/lib/saab/"

sites:
  ECSE318:
    url: "url1"
    user: "username1"
    password: "password1"
    user_db: "something for future"
    ping_role_id: 238423 # some role id number from discord
  ECSE485:
    url: "url2"
    user: "username2"
    password: "password2"
    user_db: "something for future 2"
    ping_role_id: 238423 # some role id number from discord
  ECSE315:
    url: "url3"
    user: "username3"
    password: "password3"
    user_db: "something for future 2"
    ping_role_id: 238423 # some role id number from discord
